#!/usr/bin/sh

# Installs mandoc
# THIS MUST BE THE FIRST SET INSTALLED
sudo pacman -S --noconfirm man-db man-pages

# Neovim will to be the primary editor
sudo pacman -S --noconfirm neovim

# This section installs tools that are important for downloading files from
# different sources, including some that will be used during setup.
sudo pacman -S --noconfirm curl wget
sudo pacman -S --noconfirm git lazygit

# OpenSSH and GnuPG
sudo pacman -S --noconfirm openssh gnupg

# Installs login greeter
sudo pacman -S --noconfirm greetd greetd-tuigreet

# Mount and unmount USB devices
sudo pacman -S --noconfirm udisks2

## START TERMINAL SECTION

# -- Z Shell
sudo pacman -S --noconfirm zsh zsh-syntax-highlighting zsh-theme-powerlevel10k

# -- tmux is a must have
sudo pacman -S --noconfirm tmux

# -- TaskWarrior
sudo pacman -S --noconfirm task vit

# -- Some other useful TUI applications
sudo pacman -S --noconfirm xplr vifm neofetch unzip

## Install Yay
sudo pacman -S --noconfirm --needed git base-devel && mkdir $HOME/.local/tmp && cd $HOME/.local/tmp && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd .. && rm -rf yay
yay -Y --gendb --noconfirm
yay -Syu --devel --noconfirm

### INSTALL SWAY
# 
# Basics
#
sudo pacman -S --noconfirm sway swaylock swayidle swaybg waybar foot polkit
sudo pacman -S --noconfirm waybar ttf-font-awesome ttf-roboto-mono-nerd wofi
sudo pacment -S --noconfirm brightnessctl autotiling-rs gammastep mako

yay -S --noconfirm sworkstyle

## GUI Applications
# -- Firefox
sudo pacman -S --noconfirm firefox


### Dev Tools
#
# -- Programming Languages
sudo pacman -S --noconfirm go gopls
yay -S --noconfirm golangci-lint

#
# -- Nodejs/npm
sudo pacman -S --noconfirm npm

#
# -- Podman
sudo pacman -S --noconfirm podman podman-compose podman-docker

